language: cpp
sudo: true
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libboost-all-dev
      - cmake

before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then yes | sudo add-apt-repository ppa:axel-huebl/cmake3.1; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get install cmake libboost-dev; fi

  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update && brew upgrade; fi

install: if [[ $TRAVIS_OS_NAME == "linux" ]] ; then sudo apt-get update -qq; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target all --
  - cmake --build . --target package --

after_script:
  - ctest
  - cmake --build . --target Experimental --

